### ISSUE TITLE
Incorrect format being written to /etc/environment

### ISSUE THREAD

**Issue by akumria** [tmatilai/vagrant-proxyconf#159]
In debugging why vagrant-proxyconf wasn't working, I stumbled over the fact that the output it generates for /etc/environment is incorrect.

See http://man7.org/linux/man-pages/man5/pam_env.conf.5.html

Unfortunately https://github.com/tmatilai/vagrant-proxyconf/blob/c87058dac3a50ef7f38cad3e94f30d4ffcb72582/lib/vagrant-proxyconf/config/env_proxy.rb#L49 appears to prefix values with 'export'.

**Comment by tmatilai** [comment]
Hmm, that should not be the case. The `export` should only be output to `/etc/profile.d/proxy.sh`. `/etc/environment` is generated by [this method](https://github.com/tmatilai/vagrant-proxyconf/blob/v1.5.2/lib/vagrant-proxyconf/action/configure_env_proxy.rb#L87-L98) which doesn't add the `export`.

So maybe the issue is somewhere else? What shell do you use on the box?

**Comment by codylane** [comment]
This shouldn't be a problem anymore due merge.  Closing.

Feel free to re-open if it's still an issue.
