### ISSUE TITLE
Enable proxy for Yarn

### ISSUE THREAD

**Issue by heron182** [tmatilai/vagrant-proxyconf#165]
It would be nice if the plugin also set the necessary proxy configuration for `yarn`, just like `npm`.

```
yarn config set http-proxy $http_proxy
yarn config set https-proxy $https_proxy
```

**Comment by tmatilai** [comment]
Sure. If that is how it works, it should be quite straightforward to implement. Waiting for the pull request. =)

**Comment by codylane** [comment]
No further response heard about this issue and I assume this is finally stale.  

That said, if you would like us to work on this feature, I would strongly recommend that we have some sort of community opt in about how useful this feature would be for others. I've used thumbsup emojis in the past but I'm open to other ideas as well.  I'd love to know how useful this integration might be for others but since this is now 3 years old and never got any traction I'm going to close it.

Also I'm not such what yarn is, how it's used and what it's supposed to do so it's hard for me to even provide a solution without further context, documentation and examples.
