### ISSUE TITLE
Proxyconf fails on CentOS when using docker-latest instead of docker

### ISSUE THREAD

**Issue by tookko** [tmatilai/vagrant-proxyconf#166]
When a CentOS guest has docker-latest installed but not docker, proxyconf will fail:

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
systemctl restart docker || service docker restart || /etc/init.d/docker restart
Stdout from the command
Stderr from the command:
Failed to restart docker.service: Unit not found.

...and so on. The check for whether docker is installed or not should not assume systemd has docker.service, as for users using docker-latest the service name is docker-latest.service.

**Comment by tookko** [comment]
In case anyone else has the same problem, a workaround is symlinking docker.service to docker-latest.service

**Comment by codylane** [comment]
I don't really understand how you have installed docker into your vagrant VM and what your Vagrantfile looks like.  If you have provide those details it might help us troubleshoot your issue further.  

I've solved some issues with docker in the 2.0.0 version of this plugin and I'm curious if this issue still remains.   Please report back.

**Comment by codylane** [comment]
No further details have been provided and the `2.0.x` version of the plugin handles more robust configuration around docker.  Closing out this issue due to lack of details.  

If you re-open this issue, please provide adequate details about your environment.

1. What OS are you using?
2. What version of vagrant is installed?
3. Please provide the output`vagrant plugin-list`
4. Please provide the `Vagrantfile` and any provisioning scripts that you use to configure your guest.
