### ISSUE TITLE
Cannot add PPA: user or team does not exist

### ISSUE THREAD

**Issue by forseti** [tmatilai/vagrant-proxyconf#171]
Hi there,

I'm currently having problem adding apt repository

After I did `vagrant ssh`

I ran the following command:

Command:
`sudo apt-add-repository ppa:ansible/ansible`

Output:
> Cannot add PPA: 'ppa:~ansible/ubuntu/ansible'.
> ERROR: '~ansible' user or team does not exist.

I wonder if I missed anything during configuration?

Thanks a ton!!

Donny

**Comment by oh4** [comment]
I'm also experiencing the same issue. Running Ubuntu 16.04 LTS I can `sudo apt-get install software-properties-common` just fine and install any packages including running `update` and `upgrade` so it's definitely not a proxy issue. However, when I run `sudo apt-add-repository ppa:ansible/ansible`, I get the following:

> Cannot add PPA: 'ppa:~ansible/ubuntu/ansible'.
> ERROR: '~ansible' user or team does not exist.

**Comment by forseti** [comment]
Hi @tmatilai 

I've tried
`sudo -E apt-add-repository ppa:ansible/ansible`
It returned same error message.

Thanks!!
Donny

**Comment by fahiddin** [comment]
Hi,

I'm on Ubuntu 16.04 LTS as well, and am encountering the same error. I actually encountered it a few months ago when first installing Ansible. I tried all the workarounds I found online including -E. I recently  saw a suggestion of adding Defaults env_keep="http_proxy https_proxy". I can install software-properties-common and do an upgrade/update, so it's definitely not that.

Has anyone managed to get past this? It sucks because I want to use a few module arguments that are not in the 2.0 version of ansible (i.e. path for lineinfile!)

Thanks!

**Comment by radioactive73** [comment]
I was able to get this to work (in bionic) by manually adding the repo to /etc/apt/sources.list - for xenial it would be: deb http://ppa.launchpad.net/ansible/ansible-2.6/ubuntu xenial main
Then you should be able to manually ad the key: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
However since I'm running WSL I had to use a workaround for the key: curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x93C4A3FD7BB9C367" | sudo apt-key add
Hope this helps.

**Comment by pezhore** [comment]
@radioactive73 That worked for me on my Ubuntu 18.04 WSL instance.

**Comment by codylane** [comment]
Hi Guys,

I'm having a hard time trying to understand this issue and whether or not it relates to the vagrant-proxyconf plugin.  To me there isn't enough information to determine if this is an issue with the plugin or it's an issue with something else either the Ubuntu distro, apt, ansible... etc.

If this is an issue with this plugin please provide these details:

* Please provide the vagrant version you are using.
* Please provide what type of workstation you use as well as the version of OS that is installed.
* Please provide the version of the vagrant-proxyconf version that you have installed.
* Please provide an example Vagrantfile and provisioning scripts in order to reproduce this problem.  
* Any additional steps to reproduce this behavior.

Because this issue doesn't appear to be related to vagrant-proxyconf plugin, i'm going to close out this issue.  If you would like to provide the details I've requested above please feel free to re-open this issue.

**Comment by Jummartinezro** [comment]
> I was able to get this to work (in bionic) by manually adding the repo to /etc/apt/sources.list - for xenial it would be: deb http://ppa.launchpad.net/ansible/ansible-2.6/ubuntu xenial main
> Then you should be able to manually add the key: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
> However since I'm running WSL I had to use a workaround for the key: curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x93C4A3FD7BB9C367" | sudo apt-key add
> Hope this helps.

Worked for me :+1: 

Lasts step I had to:  
[Add the source list manually](https://askubuntu.com/a/777770)

(Add the key  manually)[https://stackoverflow.com/questions/21338721/gpg-no-valid-openpgp-data-found]

**Comment by boillodmanuel** [comment]
On my side, it was a proxy / firewall issue. 
I was able to add ppa after opening:
- `*.ubuntu.com`
- `launchpad.net`
- `*.launchpad.net`

**Comment by poige** [comment]
It's solely and completely Ubuntu's fault and they do have a bug report in regards: https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1781917

That cryptic message can arise from various networking malfunction starting from DNS and you name it.

**Comment by markuszeller** [comment]
I had the same error and found out python was blocked in the firewall.

**Comment by akontsevich** [comment]
So how to solve? Need to install this:
https://answers.launchpad.net/ubuntu/+source/git-cola/+question/695751

**Comment by codylane** [comment]
@akontsevich - I'm not sure why you posted to this thread, your response is not a solution and it's phrased like a question.  It is confusing and probably is confusing for others. 

Given all the other responses it appears that this is a bug or a bad configuration in your guest VM.

I'm not sure I understand this issue and I've not been able to reproduce this over the past few years.  However, if it were me the first things I would check are the following:

* Ensure that your date and time on your VM are in sync with your host. If the time is out of sync on your VM you will have encryption issues when talking to https endpoints.  Here's an article that may help setup NTP on your guest VM.  https://ubuntu.com/blog/ubuntu-bionic-using-chrony-to-configure-ntp

* Check the firewall on your guest VM and ensure their rules are allowed to communicate properly to remote hosts. When attempting to communicate with the PPA and it appears to hang then you might want to try using `strace` on the pid and or try disabling your firewall altogether to see if the issue still remains.  Lastly, you could also use `tcpdump` to capture some packets while you are attempting to make a connection to the PPA in question and then use `wireshark` to analyze the packet to see what's going on.  

* You could also try this https://github.com/tmatilai/vagrant-proxyconf/issues/171#issuecomment-559461150

* You could also try using `curl` to attempt communication with the remote PPA something like `curl -vk http://ppa.launchpad.net/ansible/ansible-2.6/ubuntu` and curl should use the proxy configuration. If curl works, then it must be a bad configuraiton in your apt sources or a bug.

Anyway, I hope this helps others troubleshoot this as well.  I wish I was able to reproduce this.

**Comment by akontsevich** [comment]
@codylane I'm not in VM and time is ok (NTP is set). I just saw you had same issue and probably have a solution. The problem here probably is https://launchpad.net/ubuntu/+source/git-cola - is not a PPA. Adding PPA manually could not work as I do not know exact URL and where to take the key.

**Comment by codylane** [comment]
> @codylane I'm not in VM and time is ok (NTP is set). 

I'm not sure I understand your issue then. If you are not inside a VM then you are not using Vagrant and this plugin which is not related to this thread.  Also, no, "I did not have this issue!" I'm the maintainer and developer of vagrant-proxyconf.

If you do post again, please make sure to provide the following as stated above https://github.com/tmatilai/vagrant-proxyconf/issues/171#issuecomment-478700232, as well as any other steps to attempt to reproduce the error so that we can try and help you. 

Otherwise, if you are not using vagrant-proxyconf I'm afraid this is not the right place to ask for IT support.

**Comment by sanfx** [comment]
> I was able to get this to work (in bionic) by manually adding the repo to /etc/apt/sources.list - for xenial it would be: deb http://ppa.launchpad.net/ansible/ansible-2.6/ubuntu xenial main Then you should be able to manually add the key: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 However since I'm running WSL I had to use a workaround for the key: curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x93C4A3FD7BB9C367" | sudo apt-key add Hope this helps.

Useful in installing ansible in minimal/xenial vagrant box. thanks

**Comment by dotnixx** [comment]
Well, got this message in a new linux box setup for a lab, the issue was I forgot to configure the DNS servers, it worked after I set it up.
