### ISSUE TITLE
Docker provider: Guest-specific operations were attempted on a machine that is not ready for guest communication.

### ISSUE THREAD

**Issue by h-no** [tmatilai/vagrant-proxyconf#181]
When vagrant-proxyconf is installed I get an error message (see below) when starting a container by running `vagrant up` for the first time. It seems to work if I run `vagrant up` a second time.
I initially wrote an issue for the vagrant project, but later discovered that it worked when uninstalling the plugin, so I'm filing the issue here instead. (That's why the issue follows their template....)

### Vagrant version
Vagrant 2.2.3

### vagrant-proxyconf version
vagrant-proxyconf (2.0.0, global)

### Host operating system
macOS Mojave Version 10.14.2

### Guest operating system
Docker provider, https://hub.docker.com/_/hello-world

Docker Community Edition Version 2.0.0.2 (30215)
Docker Engine version 18.09.1, build 4c52b90

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "hello-world"
  end
end
```

### Debug output
First run: https://gist.github.com/h-no/d17bab1f77ffbe06f27689935e4d50a4
Second run: https://gist.github.com/h-no/7f877971dd533bce9d1374db953b8aa2

### Expected behavior
Container should've run on initial `vagrant up` command, independently of vagrant-proxyconf plugin is installed or not.

### Actual behavior
Running `vagrant up` doesn't start container, instead gives an error.
Running `vagrant up` again immediately after, the output is different.
```
❯ vagrant up
Bringing machine 'default' up with 'docker' provider...
==> default: Creating the container...
    default:   Name: test_default_1547634778
    default:  Image: hello-world
    default: Volume: /Users/hannesna/vagrant/test:/vagrant
    default:
    default: Container created: b2769a85f40c5532
==> default: Starting container...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

❯ vagrant up
Bringing machine 'default' up with 'docker' provider...
==> default: Vagrant has noticed that the synced folder definitions have changed.
==> default: With Docker, these synced folder changes won't take effect until you
==> default: destroy the container and recreate it.
==> default: Starting container...
==> default: Provisioners will not be run since container doesn't support SSH.
```
### Steps to reproduce
1. Create Vagrantfile with contents above
2. Run `vagrant up` and notice that the container doesn't start and the error message
3. Run `vagrant up` again, the container starts with different message
4. Run `vagrant destroy`
5. Run `vagrant plugin uninstall vagrant-proxyconf`
6. Run `vagrant up` and notice that container starts ok

**Comment by codylane** [comment]
I apologize for the problems, I hope to be able to have time to take a look into this in the new few days.  Thank you for reporting and for providing all those details.

**Comment by codylane** [comment]
I've not had time to test this yet, but I noticed a few minor things that may contribute to the behavior your are seeing.

The first is, I've not tested this plugin on` VirtualBox 6.x` or `Vagrant 2.2.3` and I noticed this in your [debug log](https://gist.github.com/h-no/d17bab1f77ffbe06f27689935e4d50a4#file-vagrant-log-L293).  This plugin may work with those versions, however, I've not been able to test those versions. It could be possible there is a problem there as well but I cannot say for certain.  

**Disclaimer** - These are my words and I'm just a contributer but I feel that this plugin is hard to grasp and understand when looking at the code and I believe the issue you are seeing is buried deep in the code and possibly in areas of it that I just don't understand well enough to sort out.  I suspect the problem is manifesting in [is_enabled.rb](https://github.com/tmatilai/vagrant-proxyconf/blob/master/lib/vagrant-proxyconf/action/is_enabled.rb#L10-L14) where the container is trying to be configured when not in the `:running` state, but like I said, I'm not sure if making a change there would cause different problems down the road.

When `vagrant-proxyconf` `2.0.0` is installed as a plugin, by default it will attempt to configure a proxy which means that the plugin attempts to enable all the proxy providers by default, which _may_ cause issues with some folks setups.  

If you don't want to go through the hassle to uninstall the `vagrant-proxyconf` everytime you want to disable the plugin you can do something like this in the `Vagrantfile`

FYI - This should be a workaround for the behavior that you are seeing and I would highly recommend all your Vagrantfile's be updated to use this pattern if the `vagrant-proxyconf` plugin is installed. 
```
Vagrant.configure("2") do |config|

    if Vagrant.has_plugin?("vagrant-proxyconf") && ENV['HTTP_PROXY'].nil? == false
      config.proxy.http      = "#{ENV['HTTP_PROXY']}"
      config.proxy.https     = "#{ENV['HTTPS_PROXY']}"
      config.proxy.no_proxy  = "#{ENV['NO_PROXY']}"
      config.apt_proxy.http  = "http://#{ENV['HTTP_PROXY']}"
      config.apt_proxy.https = "http://#{ENV['HTTPS_PROXY']}"
    else
      # If we get here either the vagrant-proxyconf is not installed or the current USER environment 
      # does not have the HTTP_PROXY environment variables set.
      # so we disable all vagrant-proxyconf plugins.
      config.proxy.enabled = false
    end

    config.vm.provider "docker" do |d|
      d.image = "hello-world"
    end
end
```

We've attempted to highlight this in the [documentation](https://github.com/tmatilai/vagrant-proxyconf#disabling-the-plugin).  I do agree the plugin needs some more clean up as well as documentation overhaul but my time is limited.  If you have time to troubleshoot and implement a fix, we will accept a pull request.  

Thanks for reporting this issue.

**Comment by codylane** [comment]
I've determined this message 

```
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

 is caused due to a race condition that happens when using docker and the container is in the `:stopped` state, so there needs to be some new logic in [is_enabled.rb](https://github.com/tmatilai/vagrant-proxyconf/blob/master/lib/vagrant-proxyconf/action/is_enabled.rb#L11) to wait for the "guest" to be in the running state before it can be configured.

**Comment by tmatilai** [comment]
Sorry, too tired now to dive into the debug logs and code, but Vagrant has a `WaitForCommunicator` action that should be earlier in the middleware stack. So there really is something strange (or regression) there.

**Comment by h-no** [comment]
@codylane Let me know if you need help reproducing, I manage to reproduce it 100% on two different computers.

**Comment by codylane** [comment]
FYI - The pull request I just linked to this issue should address the first issue;

The `vagrant-proxyconf` plugin is installed
AND
no `config.proxy.*` are set in a Vagrantfile

```
Vagrant.configure("2") do |config|

    config.vm.provider "docker" do |d|
      d.image = "hello-world"
    end
end
```
The pull request addresses this problem by `disabling` the `vagrant-proxyconf` plugin.  

The second feature of this pull request is to add additional logic to check if a proxy should be configured

Given either of the following environment variables being set

`export HTTP_PROXY=http://$my_proxy_host:$my_proxy_port`
or
`export HTTPS_PROXY=https://$my_proxy_host:$my_proxy_port`

AND

Given this Vagrantfile

```
Vagrant.configure("2") do |config|

    if Vagrant.has_plugin?("vagrant-proxyconf")
      config.proxy.http      = "#{ENV['HTTP_PROXY']}"
      config.proxy.https     = "#{ENV['HTTPS_PROXY']}"
      config.proxy.no_proxy  = "#{ENV['NO_PROXY']}"
    end

    config.vm.provider "docker" do |d|
      d.image = "hello-world"
    end
end
```
The `vagrant-proxyconfg` plugin would be enabled for all capable providers on the guest.  However, if you didn't set `HTTP_PROXY` or `HTTPS_PROXY` in your environment before running `vagrant up` or `vagrant provision` then there is new logic to `disable` `vagrant-proxyconf` from attempting to configure your guest.

The new logic is an attempt to *auto-configure* the `vagrant-proxyconf` providers based off your current environment proxy variables.

**Comment by codylane** [comment]
2.0.1 has been released. Please re-open if this is still an issue.
