### ISSUE TITLE
Can't install vagrant-proxyconf because of proxy

### ISSUE THREAD

**Issue by nickderv** [tmatilai/vagrant-proxyconf#184]
I am trying to install proxyconf in windows 10 behind a corporate proxy. When I am doing:
`vagrant plugin install vagrant-proxyconf`
the result is:
```
Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
```
Does anybody know how to overcome the proxy issue?

**Comment by tmatilai** [comment]
Vagrant should support the standard `HTTPS_PROXY` etc environment variables.

**Comment by codylane** [comment]
Assuming that your proxy is setup on your system properly, you could open your browser to this:
https://rubygems.org/gems/vagrant-proxyconf and download the gem manually.  

Then you could install like so [this is a MacOS example].  I don't have a windows machine so I cannot provide an example. 

#### `vagrant plugin install ./vagrant-proxyconf-2.0.0.gem`

```
Installing the './vagrant-proxyconf-2.0.0.gem' plugin. This can take a few minutes...
Installed the plugin 'vagrant-proxyconf (2.0.0)'!
```

This might also help.  https://mtdevuk.com/2014/11/25/using-vagrant-when-behind-a-proxy-server/

Closing issue as installing the plugin is workstation specific and not a problem with this module.  If you should notice problems with this module please open a new request.  Thanks.

**Comment by nickderv** [comment]
@codylane I followed your example and I got the same error:

```
vagrant plugin install '.\vagrant-proxyconf-2.0.0 (1).gem'

Installing the '.\vagrant-proxyconf-2.0.0 (1).gem' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
```
Any ideas?

**Comment by codylane** [comment]
@nickderv - Yes, I feel like I've provided you with adequate information to get you going and the examples I provided should have worked for you to install the plugin.  If you are still experiencing issues installing I'd highly recommend that you work with your IT staff and or teammates at work.   The issue you are experiencing is workstation and company policy specific.

I don't personally use windows or have any ability to test this plugin on windows.  

I will also state that as with most open source projects we rely on the community to help us test and development integrations for multiple platforms and not all of us are experts in all fields.  With that said, I cannot say for certain what types of problems you'll run into since you are using windows.
