### ISSUE TITLE
vagrant-proxyconf running on Win10 and provisioning with Docker

### ISSUE THREAD

**Issue by wangkexiong** [tmatilai/vagrant-proxyconf#186]
I'm running vagrant on Win10 and installed vagrant-proxyconf plugin.

However when configuring docker proxy, it reports 
......vagrant-proxyconf-2.0.0/lib/vagrant-proxyconf/action/configure_docker_proxy.rb:50:in `write': No such file or directory @ rb_sysopen - /tmp/vagrant-proxyconf-docker-config.json (Errno::ENOENT)

Er, it is really no /tmp directory on a windows system, I tried to change the definition of 
          @docker_client_config_path = "/tmp/vagrant-proxyconf-docker-config.json" to 
          @docker_client_config_path = "vagrant-proxyconf-docker-config.json"

another issue reported:
vagrant-proxyconf-2.0.0/lib/vagrant-proxyconf/action/configure_docker_proxy.rb:93:in `unlink': Permission denied @ unlink_internal - vagrant-proxyconf-docker-config.json (Errno::EACCES)

On my Centos Workstation, it works well. Do we have plan to support this beautiful plugin working on windows?

**Comment by sdaoudi** [comment]
Hi @wangkexiong 

I have the same issue with Windows 10.

To resolve this,  I use temporary the version 1.5.2 of vargrant-proxyconf plugin:

`vagrant plugin install vagrant-proxyconf --plugin-version 1.5.2`

**Comment by codylane** [comment]
Hi @wangkexiong @sdaoudi - I'm sorry to hear that this doesn't work so well on Windows based hosts.  It's hard to maintain such a wide scope of features on different operating systems.  I'm also not much of a windows user so I'm not much help to create/fix the windows implementation.

I know this is a long shot, but is it possible to install cygwin on your windows based machine?  If so, I'd love to know if this issue is resolved?  I don't have a windows machine to test this on otherwise I would provide a solution.

**Comment by codylane** [comment]
This should be fixed by the `2.0.1` release which I hope to have out in the next week or so.  
See related issue: #187

**Comment by sdaoudi** [comment]
Thanks @codylane

**Comment by codylane** [comment]
2.0.1 has been released. Please re-open if this is still an issue.
