### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Ciribomflax** [tmatilai/vagrant-proxyconf#214]
Can't run the install command because I am behind a proxy. This is the most useless plugin I have ever seen.

**Comment by codylane** [comment]
hi @Ciribomflax - Thank you for reporting your problem to this repository.  In order to better help you though, I'll need to know a little more about what is not working.  The scenario you describe does indeed work and many, many people are able to install this plugin either behind a proxy or not so the issue describe is probably not a problem with our plugin but more or less a problem with your workstation and company network policies.  I'd try and sort out your internet connectivity issue with your IT staff before attempting to install this plugin.  

FWIW, please refrain using offensive language like "This is the most useless plugin I have ever seen." That is not a valid comment nor is it helpful to anyone.  Keep in mind I don't get paid to maintain this plugin and I do all of this for free.  So don't get mad if things don't work!  Instead consider contributing constructive feedback with screenshots and ways to reproduce the issue you are having so that we can better help you isolate your problem.  **The current issue you reported IS NOT a problem with this plugin or the ability to install the plugin.**

**Comment by codylane** [comment]
Closing this issue as it is irrelevant to this plugin and is total trolling.  

I guess it's time to seriously consider getting a code of conduct clause in place.  Thanks for the reminder.  Have a good day.

**Comment by tmatilai** [comment]
@Ciribomflax Of course this plugin can't help before it is installed. But even then, it only configures the guest machines. The good news is that Vagrant supports standard `http_proxy` and `https_proxy` environment variables for fetching plugins and boxes. You can also download a plugin directly from Rubygems and install is from a local file.

**Comment by tmatilai** [comment]
@codylane +1 for code of conduct. I have added it for my later projects.
