### ISSUE TITLE
vagrant won't read user profile config ~./docker/config.json

### ISSUE THREAD

**Issue by adespain** [tmatilai/vagrant-proxyconf#219]
This is where I first reported my issue: 

https://github.com/awslabs/amazon-ecr-credential-helper/issues/207

When I try to use amazon-ecr-credential-helper with a vagrant machine it fails.  Vagrant will try to read the /etc/docker/config.json file instead of the user profile ~/.docker/config.json.  Is there a way to tell vagrant to check the user profile config before checking the /etc/docker/config.json?

**Comment by codylane** [comment]
This is is related to #218, all further updates will be there. I'm going to close this out for now.  Please provide additional information to help support this feature/bug fix in issue #218 so that I can better reproduce this on my side. 

I'd love to see some examples of what things look like before and after.
