### ISSUE TITLE
no_proxy configuration ignored with libvirt/qemu kvm provider

### ISSUE THREAD

**Issue by benbugohit** [tmatilai/vagrant-proxyconf#235]
Tried adding a .example.foo.domain in "VAGRANT_NO_PROXY" and "no_proxy" variables in CentOS7 host, 
- vagrant 2.2.14, 
- vagrant-proxyconf 2.0.10, 
- vagrant-libvirt 0.4.1
.
Tried also adding 
- config.proxy.no_proxy in Vagrantfile
This resulted in ignored "no proxy" configuration in yum repos which baseurl contained ".example.foo.domain" deployed by ansible 2.9.15 provisionner with yum_repository plugin in a CentOS 7 guest.

**Comment by benbugohit** [comment]
Digged into code, reported behavior seems to be "normal" regarding /etc/yum.conf updating, 
not specific /etc/yum.repos.d/* files which contain baseurl ending with ".example.foo.domain".

So this bug seems to be a feature request

**Comment by codylane** [comment]
Hello @benbugohit,

Thank you for reporting the issue. I won't lie that I am having a bit of a hard time trying to understand the exact issue you are having and I am hoping we can work together to diagnose and resolve (*if there is a solution*). 

I am wondering if you could please try and provide some examples of what the expected behavior is and potentially a way I can try and reproduce this? I think I am understanding your issue is that you want to add a **no_proxy** in a repo file in `/etc/yum.repos.d/*`?

After consulting the [yum.conf](https://linux.die.net/man/5/yum.conf) documentation and searching the internet, I am not sure that yum actually has the notion of the `no_proxy` setting or environment variable.  

Here's are all the settings for `proxy` from the yum.conf. 

- **proxy** URL to the proxy server for this repository. Set to '_none_' to disable the global proxy setting for this repository. If this is unset it inherits it from the global setting

- **proxy_username** username to use for proxy. If this is unset it inherits it from the global setting

- **proxy_password** password for this proxy. If this is unset it inherits it from the global setting

**Comment by codylane** [comment]
No further information received and it doesn't appear that yum has a `no_proxy` option. However that said, I do wonder if you could work around this by using ansible by adding ```proxy=_none_``` in your repo file in question as stated in the man page for yum.conf.
