### ISSUE TITLE
problem with https yum proxy

### ISSUE THREAD

**Issue by joawin** [tmatilai/vagrant-proxyconf#238]
Hi,
i am not able to use `config.yum_proxy.https` in vagrant-proxyconf
```
#<VagrantPlugins::ProxyConf::Config::Key:0x00000000030ef030>=http://10.XX.XX.XX:3128/
       :
       * The following settings shouldn't exist: https
      
```
If i only use `config.yum_proxy.http` it works. 

```
$ vagrant plugin list

vagrant-berkshelf (5.1.2, global)
vagrant-hostmanager (1.8.9, global)
vagrant-proxyconf (2.0.10, global)
```

Can someone verify if https is working with yum ?

**Comment by chucknelson** [comment]
@joawin - I think this is expected, as the `yum` proxy config [doesn't use an `https` option if you reference the `yum`-specific env vars](https://github.com/tmatilai/vagrant-proxyconf#environment-variables-1).

I think this makes sense since `yum` only has a singular `proxy` config which you can also see when referencing docs for yum (e.g., like [some Fedora docs here](https://docs.fedoraproject.org/en-US/Fedora_Core/5/html/Software_Management_Guide/sn-yum-proxy-server.html), or [docs here](https://docs.openathens.net/display/public/LA/Configuring+yum+to+use+a+proxy+server)).

So when setting the singular setting (which it looks like you're doing), `yum` should work as expected.

Is that not the case? Not sure if you tried to run `yum` without the invalid `https` setting.

**Comment by codylane** [comment]
Excellent explanation and thank you. While I am no longer going to contribute to this project since Vagrant is moving from Ruby to Go (See [issues](https://github.com/tmatilai/vagrant-proxyconf/issues/237) for details) I appreciate your help @chucknelson. I hope you are well and thank you helping out on this.

**Comment by codylane** [comment]
No further context has been provided and @chucknelson has provided all the information needed to get this working.
