### ISSUE TITLE
proxy settings not propagated to docker?

### ISSUE THREAD

**Issue by dkoper** [tmatilai/vagrant-proxyconf#97]
Not sure if this is a feature request or a bug.
I'm behind a corporate proxy, so need http proxy on all Internet connections.
My Vagrantfile includes:

```
Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider(:virtualbox) do |v|
...
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http        = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https        = ENV["https_proxy"]
    end
  end

  config.vm.provision('docker')
end
```

and http_proxy envs are exported on my ubuntu 14 machine. Box is downloaded successfully, docker is successfully provisioned, but when I `vagrant ssh` and `docker pull <img>`, I get a `connection timed out`. When I manually add http_proxy vars to /etc/default/docker and `service docker restart`, docker pull works fine.
Isn't vagrant-proxyconf supposed to set it for me automatically? If not, how can I configure it to do so? 
I'm using vagrant-proxyconf 1.4.0 and latest vagrant.

**Comment by kartikgupta0909** [comment]
This is my Vagrant file
Vagrant.configure("2") do |config|
  config.proxy.http = "http://proxy.iiit.ac.in:8080"
  config.proxy.https = "https://proxy.iiit.ac.in:8080"
  config.proxy.no_proxy = "localhost,127.0.0.1"
  config.vm.box = "hashicorp/precise64"
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 15672, host: 15672
  config.vm.network "forwarded_port", guest: 3305, host: 3305
  config.vm.provision "docker" do |d|
    d.run "johnlzeller/rabbitmq-app",
      args: "-d -p 5672:5672 -p 15672:15672 -p 4369:4369 --name='rabbitmq'"
    d.run "johnlzeller/mysql-app",
      args: "-d -p 3306:3306 --name='mysql'"
    d.run "johnlzeller/buildbot-app",
      args: "-d -p 8000:8000 --link=mysql:sql --name='buildbot'"
    d.run "johnlzeller/buildapi-app",
      args: "-d -p 8888:8888 --link=rabbitmq:mq --link=mysql:sql --name='buildapi'"
  end
end

Now when i run this , it gives me an error 
Unable to find image 'johnlzeller/rabbitmq-app:latest' locally
time="2015-02-16T17:34:53Z" level="fatal" msg="Error: 404 page not found" 
I think this happens because it tries to access the containers before setting the proxy for docker, can you help me how to fix this?

**Comment by otahi** [comment]
@kartikgupta0909, Can you give more information?
I think it is not a problem of vagrant-proxyconf because `Error: 404` shows us the target server or your proxy server returns an error. If vagrant-proxyconf does not work, I think it will cause a DNS error or a TCP socket error or something...

So Please give;
- Which versions do you use?
  - vagrant
  - vagrant-proxyconf
  - docker
- Your environment variables are set on the vagrant VM?

 ```
    env | grep http
    sudo strings /proc/`pgrep docker`/environ | grep http_proxy
```
- Your proxy works fine?
  - curl to http://www.google.com/ and https://www.google.com/ is OK?
     - your configuration for https_proxy should be changed to "http://proxy.iiit.ac.in:8080". Though I think it is not related to this problem.
  - How `docker search johnlzeller/rabbitmq-app` works?
- Give detail log
  - please give us [detail log](http://docs.vagrantup.com/v2/other/debugging.html) and put it onto Gist.

Thank you,

**Comment by kartikgupta0909** [comment]
@otahi 
Vagrant Version: 1.7.2
Docker Version: 1.5.0
Outputs
 sudo strings /proc/`pgrep docker`/environ | grep http_proxy :
 http_proxy=http://proxy.iiit.ac.in:8080/

env | grep http:
 http_proxy=http://proxy.iiit.ac.in:8080/
https_proxy=https://proxy.iiit.ac.in:8080/
And yes curl and wget commands work fine
And this is the link to the log:
https://gist.github.com/kartikgupta0909/a3375ef3812dbadd5c6d

**Comment by otahi** [comment]
@kartikgupta0909 Docker 1.5 reminds me #109. Can you try `no_proxy` with `.sock`?

**Comment by kartikgupta0909** [comment]
@otahi 
I tried this , still not working.
One thing i want you to note is that , whenever i run vagrant up , i cant actually see the log where proxy is being configured for docker , but when i remove the part the application part from my vagrant file , i can actually see a log which says configuring proxy for docker.

**Comment by otahi** [comment]
@kartikgupta0909 I am sorry that I could not see the log file at that time.

I had to asked you this point at the first. It is very important point.
> One thing i want you to note is that , whenever i run vagrant up

I am checking the log and there is not log for Docker proxy as you said. Vagrant-proxyconf for Docker  expect Docker is installed before configuration. If there is no Docker on the VM, vagrant-proxyconf does not configure proxy for Docker. When you reload vagrant with `vagrant reload` or use Docker pre-installed image, vagrant-proxyconf will configure proxy. 

By the way, you mentioned;
> sudo strings /proc/pgrep docker/environ | grep http_proxy :
> http_proxy=http://proxy.iiit.ac.in:8080/

If Docker have `http_proxy`, it can access with the proxy server. Can you check the following commands because I want to check the Docker process really have `http_proxy` environment?

```
pgrep -l docker
sudo cat /proc/<<process ids above>>/environ
```

Thank you,

**Comment by Clueless76** [comment]
@otahi I will take over this thread because I run exaclty the same issue as kartikgupta0909 but still didn't found a solution.

Vagrant version is 1.7.2
Docker version is 1.5

Here the result:
vagrant@vagrant:~$ sudo cat /proc/779/environ
UPSTART_INSTANCE=no_proxy=localhost,127.0.0.1METHOD=dhcpLOGICAL=eth0NO_PROXY=localhost,127.0.0.1ADDRFAM=inetUPSTART_JOB=dockerhttp_proxy=http://10.1.3.3:3128/TERM=linuxPATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/binIFACE=eth0UPSTART_EVENTS=local-filesystems net-device-upPWD=/HTTP_PROXY=http://10.1.3.3:3128/

Here is the Vagrant file:

Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.synced_folder "../user-registration-application/target", "/target", create: true
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 9200, host: 9200

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://10.1.3.3:3128/"
    config.proxy.https    = "http://10.1.3.3:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision "docker" do |d|
    d.build_image "--tag=java /vagrant/java"
    d.build_image "--tag=tomcat /vagrant/tomcat"
    d.build_image "--tag=kibana /vagrant/kibana"
    d.build_image "--tag=elasticsearch /vagrant/elasticsearch"
    d.build_image "--tag=logstash /vagrant/logstash"
    d.build_image "--tag=user-registration /vagrant/user-registration"
    d.run "elasticsearch",
      args: "-p 9200:9200"
    d.run "kibana",
      args: "-p 8080:8080"
    d.run "logstash",
      args: "--link elasticsearch:elasticsearch"
    d.run "user-registration",
      args: "-p 8081:8080 -v /target:/target --volumes-from logstash"
  end
end

Connection as describes worked well in http and https.

**Comment by jensklose** [comment]
please try again the no_proxy change:
    
    config.proxy.no_proxy = "/var/run/docker.sock,localhost,127.0.0.1"

I've the same issue and this was the solution.
